spring.datasource.url=${AUTH_DB_URL}
spring.datasource.username=${AUTH_DB_USERNAME}
spring.datasource.password=${AUTH_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=false
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
management.endpoint.health.show-details=never
