server.port=8084
spring.application.name=authentication-service

# Database configuration (H2 In-Memory)
spring.datasource.url=${AUTH_DB_URL:jdbc:h2:file:./data/auth-db;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.settings.web-allow-others=true

# Hibernate / JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Actuator configuration
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Custom Authentication Configs
jwt.signing-key=${JWT_SIGNING_KEY}
jwt.expiration=86400000
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{correlationId}] [%X{serviceName}] [%thread] %logger{36} - %msg%n
logging.level.com.jobseekercopilot=${APP_LOG_LEVEL:INFO}
